Miisan: Hello! What would you like to do?
Miisan: This is a {jiggle:1}{wave:2}{color:#FF0000}jiggly wavy red text{/color}{/wave}{/jiggle} example,{wait:2} and here's some {wave:2}normal wavy text{/wave}.
Miisan: Chose one of the following options:
Miisan: You chose the short dialogue.
Miisan: You chose the long dialogue.
Miisan: Let's {jiggle:1}shake things up{/jiggle} a bit!
Miisan: What would you like to do now?
You: Hello [{color:#FF0000}subject{/color}] TestKey [{color:#FF0000}test{/color}]

Miisan: You chose to stay. 
