Miisan: This is a {jiggle:1}{wave:2}{color:#FF0000}jiggly wavy red text{/color}{/wave}{/jiggle} example,{wait:2} and here's some {wave:2}normal wavy text{/wave}.
Miisan: You chose the long dialogue.
Miisan: Let's {jiggle:1}shake things up{/jiggle} a bit!
You: Hello [{color:#FF0000}subject{/color}] TestKey [{color:#FF0000}test{/color}]
Miisan: I want to try a [test2] too!
Miisan: You chose to stay. 
You: TestingTTTTTTTTTTTTTTTTTTTTTTTTTestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingestingesting
